### ISSUE TITLE
compute the number of terminal node in level 2

### ISSUE THREAD

**Issue by DWingHKL** [lifrordi/DeepStack-Leduc#21]
In lookaheadbuilder.lua (https://github.com/lifrordi/DeepStack-Leduc/blob/master/Source/Lookahead/lookahead_builder.lua) line 87 

 self.lookahead.terminal_nodes_count[2] = 2

why self.lookahead.terminal_nodes_count[2] = 2  it should be 1 because just fold action lead to terminal node.

and line 80

self.lookahead.nonterminal_nodes_count[2] = self.lookahead.bets_count[1]

if the action abstraction is FCPA. then self.lookahead.bets_count[1] is equal to 3 (C,P,A). According to _compute_tree_structures function.

so self.lookahead.nonterminal_nodes_count[2] = 3  and self.lookahead.nonterminal_nodes_count[2] + self.lookahead.terminal_nodes_count[2] = 5 > 4 (FCPA) which is confused with me.

**Comment by Kiv** [comment]
I noticed that `terminal_nodes_count` is not read anywhere in the code, so the value doesn't matter in the Leduc demo. I assume it was used for something important in the real DeepStack and was mistakenly left in.
