### ISSUE TITLE
lookahead.ranges_data tensor size

### ISSUE THREAD

**Issue by DWingHKL** [lifrordi/DeepStack-Leduc#22]
I was also confuse about Code comments said it has six dimensional tensor, but lookahead.ranges_data[1] just an five dimensional tensor .look like lose batch dimensional

line 130

--data structures [actions x parent_action x grandparent_id x batch x players x range]
  self.lookahead.ranges_data[1] = arguments.Tensor(1, 1, 1, constants.players_count, game_settings.card_count):fill(1.0 / game_settings.card_count)

**Comment by Kiv** [comment]
I also wondered about this.

I think the comment refers to a different version of the code. A batch dimension would allow to store data for different community (public) cards in that same tensor, since the different public cards don't affect the actions available in poker.

**Comment by lifrordi** [comment]
Yes, the comment is from different version of the code where we had another dimension for batch.
