### ISSUE TITLE
Converts hand range to bucket

### ISSUE THREAD

**Issue by DWingHKL** [lifrordi/DeepStack-Leduc#25]
@lifrordi hello, I was still confused about convert hand range to bucket
My question 1 is: According to your reply. Deepstack arrange  buckets  by the player's expected hand strength during training and during the continuous re-solving process. As we know normal EHS is based on the uniform of opponent private cards. But both in training and continuous re-solving process we can get opponent range(private cards distribution). So Deepstack use normal EHS(uniform) or use the opponent current range to real time compute EHS. If is later one, in my test it need more than 1 minute  to compute EHS in real time. How do you speed up that Deepstack run fast within 10s? 
Question 2 is: normal card abstraction is do offline and store the result in  file, and load the card abstraction file when playing and run cfr. So Deepstack do buckets offline or online ? offline compute Histogram and use EMD and run k-means  to produce result?

**Comment by lifrordi** [comment]
The buckets were pre-computed offline as you suggest.
