### ISSUE TITLE
(Texas Hold'em)TerminalEquity Computation， real-time or precompute table-lookup

### ISSUE THREAD

**Issue by wanghaojie1024** [lifrordi/DeepStack-Leduc#26]
@lifrordi Hello！
I have tried to construct **call_matrix** of flop using real-time computaion, it cost me about 90 second, so preflop would cost much more than 90s.
I have tried to precompute it, but to store 1000 matrix[1326*1326] requires about 40GB, it's too large to save.
I wonder how did you implement TerminalEquity in Texas Hold'em, Did you precompute it and do table lookup?
Thanks!

**Comment by lifrordi** [comment]
Hi,
yes we precomputed these tables to do a lookup.

**Comment by DWingHKL** [comment]
@lifrordi In flop have 22100  call matrix and each matrix has  1326 ＊ 1326 ＊4 B which need  155431.598 GB how can you store those matrix.

**Comment by dmorrill10** [comment]
@DWingHKL maybe double check your calculations because I get 155,431.598 **MB**, which is about 155.431 GB.
