### ISSUE TITLE
How to speed up solving from the turn card is dealt

### ISSUE THREAD

**Issue by zhoujz10** [lifrordi/DeepStack-Leduc#30]
Hi @lifrordi 
Thank you for releasing the code of DeepStack-Leduc.

In your paper, you mentioned that you generated ten million situations for the turn network in 175 core years, which means 551 core seconds for each situation.

I tried this but my code is much slower and it needs thousands of core seconds to generate one situation. There is too much matrix calculation.

So, would you please share with me how to optimize this process? Did you use some abstraction?

Thank you very much!

**Comment by ghost** [comment]
Try out the CFR+ implementation written in C with optimized code and cluster support: http://poker.cs.ualberta.ca/cfr_plus.html

**Comment by zhoujz10** [comment]
Thank you very much for sharing this with me, I'm reading the codes now.

**Comment by zhoujz10** [comment]
@Sanjo Thank you very much for sharing this with me, I'm reading the codes now.
