### ISSUE TITLE
A question about masked_huber_loss

### ISSUE THREAD

**Issue by zhoujz10** [lifrordi/DeepStack-Leduc#34]
Hi @lifrordi 
[line 57 in masked_huber_loss.lua](https://github.com/lifrordi/DeepStack-Leduc/blob/master/Source/Nn/masked_huber_loss.lua#L57) says that mask is 1 for impossible features, but I think mask should be 0 for impossible features, according to the code in bucker.lua.

This line
`local loss_multiplier = (batch_size * feature_size) / (batch_size * feature_size - self.mask_sum:sum() )` only makes sense when `mask_sum` is the sum of the count of impossible features (which are most of the features for one specific sample), right?
but when I run this code, I found that `self.mask_sum` is the sum of the count of valid buckets.

card_count = 6
board_card_count = 1
bucket_count = 36
for one specific case, valid_bucket_count = 5
And my question is, should `self.mask_sum` be 5 or 31?
Thank you very much!

**Comment by DWingHKL** [comment]
By the way, what codes do you use in  generated 4M training samples for the turn network, I also have same problem with loss, but I was fixed it. and loss is same as the paper said.

**Comment by zhoujz10** [comment]
@DWingHKL Hi, I use a cluster with 2000 cores and several GPUs to do that. I solved the game from the turn card is dealt to the end of the game, same as the author did.

Can you share with me how to fix the problem with loss? Thank you so much!

**Comment by zhoujz10** [comment]
@DWingHKL For one specific turn board, there is usually around 100 valid buckets, right? (Total bucket count is 1000). Is it because we should average the loss over the 1000 buckets so the loss is around 0.02, or is it because I ignored something important?

**Comment by DWingHKL** [comment]
When you generated turn samples you are using river network ?  I think the most is have an bug in your code.

**Comment by DWingHKL** [comment]
By the way, what the loss of the river network ?

**Comment by zhoujz10** [comment]
@DWingHKL    Hi, I didn't use a river network, instead, I solve the turn situation directly to the end of the game(using lookahead and re-solving).

Maybe there is a bug, but I can't find one. Can you share with me your experience of fixing the loss problem? Maybe I'm facing the same problem.

Thank you!

**Comment by DWingHKL** [comment]
I was fixed the bug in my lookahead process.   Does you means that you use
CFR-D for turn situation?

2018-08-08 13:15 GMT+08:00 Allen <notifications@github.com>:

**Comment by zhoujz10** [comment]
@DWingHKL No, I didn't use CFR-D. It seems that cfr-d is used to generate opponent ranges, and this is only necessary for continual re-solving. When generating train samples, I just use CFR which is the same as the code in the author's repo.

**Comment by DWingHKL** [comment]
For one turn situation , for example need 1000 iterations, in each iteartion, you solve turn and run river 1000 iteration ?

**Comment by DWingHKL** [comment]
what is you email?

**Comment by zhoujz10** [comment]
@DWingHKL  yes, exactly. I check my result by solving same turn situations using the code in [tree_cfr.lua](https://github.com/lifrordi/DeepStack-Leduc/blob/master/Source/Tree/tree_cfr.lua), the results are the same. my email is zhoujz10#163.com.
