### ISSUE TITLE
random poker situation solving

### ISSUE THREAD

**Issue by wanghaojie1024** [lifrordi/DeepStack-Leduc#5]
Hi, i am a student from HIT focus on imperfect information game. I noticed that training data are generated by solving random poker situation, and in this project, the solving algorithm is **re-sloving**, but re-solving itself needs support from neural network which are trained with training data. I am confused.  Could I understand this way: you use one sloving algorithm to solve random poker situation to generate data, then train value network; when it comes to play texas hold'em, you use another solving method (re-solving) to do real time computation based on values given by value network ?  **Or** you use re-solving to solve RIVER round random poker situation, then construct RIVER round value network, then use re-solving to solve TURN round random poker situation based on previously built value network, then construct TURN value network, then flop...then preflop?
    I am looking forward to your reply.

**Comment by CuthbertJungle** [comment]
the random situations are brute force solved on a supercomputer to initialise the neural network.

**Comment by lifrordi** [comment]
It's the first scenario.
As you correctly describe, we use SOLVING algorithm to generate data and train net.
This net is then used during RESOLVING
